{% set name = "autoviz" %}
{% set version = "0.1.808" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/autoviz-{{ version }}.tar.gz
  sha256: 0281c955ae2f269a60d6092e6240b8e0905851bf7d790f921323402322c99b24

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - xlrd
    - wordcloud
    - emoji
    - numpy >=1.25.0
    - pandas <2.0
    - pyamg
    - matplotlib-base <=3.7.4
    - seaborn >=0.12.2
    - scikit-learn
    - statsmodels
    - nltk
    - textblob
    - holoviews >=1.15.3
    - hvplot >=0.9.2
    - panel >=1.4.0
    - xgboost >=0.82,<1.7
    - fsspec >=0.8.3
    - typing-extensions >=4.1.1
    - pandas-dq >=1.29

test:
  commands:
    - ipython -c "from autoviz import AutoViz_Class"
    - pip check
  requires:
    - ipython
    - pip

about:
  home: https://github.com/AutoViML/AutoViz
  summary: Automatically Visualize any dataset, any size with a single line of code
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
