{% set name = "autoviz" %}
{% set version = "0.1.902" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/autoviz-{{ version }}.tar.gz
  sha256: df70f4aa84a5c5e1373ef9547fa5100ad73be106ff44bca31c9ee84e81032f65

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - xlrd
    - wordcloud
    - emoji
    - pyamg
    - scikit-learn
    - statsmodels
    - nltk
    - textblob
    - xgboost >=0.82,<1.7
    - fsspec >=0.8.3
    - typing-extensions >=4.1.1
    - pandas-dq >=1.29

    - numpy <1.24  # [py<310]
    - hvplot ~=0.7.3  # [py<310]
    - holoviews <=1.14.9  # [py<310]
    - panel ~=0.14.4  # [py<310]
    - param ==1.13.0  # [py<310]
    - pandas <2.0  # [py<310]
    - matplotlib-base <=3.7.4  # [py<310]
    - seaborn <=0.12.2  # [py<310]

    - numpy >=1.24.0  # [py>=310 and py<311]
    - hvplot >=0.9.2  # [py>=310 and py<311]
    - holoviews >=1.16.0  # [py>=310 and py<311]
    - panel >=1.4.0  # [py>=310 and py<311]
    - pandas >=2.0  # [py>=310 and py<311]
    - matplotlib >3.7.4  # [py>=310 and py<311]
    - seaborn >0.12.2  # [py>=310 and py<311]

    - numpy >=1.25.0  # [py>311]
    - hvplot >=0.9.2  # [py>311]
    - holoviews >=1.15.3  # [py>311]
    - panel >=1.4.0
    - pandas <2.0  # [py>311]
    - matplotlib >3.7.4  # [py>311]
    - seaborn >0.12.2  # [py>311]

test:
  commands:
    - ipython -c "from autoviz import AutoViz_Class"
    - pip check
  requires:
    - ipython
    - pip

about:
  home: https://github.com/AutoViML/AutoViz
  summary: Automatically Visualize any dataset, any size with a single line of code
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
