{% set name = "autoviz" %}
{% set version = "0.1.905" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/autoviz-{{ version }}.tar.gz
  sha256: 1c659d5957340301bc32818b0362f5065d23ca391e8bc1690af2db2e40b255ef

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - xlrd
    - wordcloud
    - emoji
    - pyamg
    - scikit-learn
    - statsmodels
    - nltk
    - textblob
    - xgboost >=0.82,<1.7
    - fsspec >=0.8.3
    - typing-extensions >=4.1.1
    - pandas-dq >=1.29

    - numpy >=1.24.0
    - hvplot >=0.9.2
    - holoviews >=1.16.0
    - panel >=1.4.0
    - pandas >=2.0
    - matplotlib-base >3.7.4
    - seaborn >0.12.2

test:
  commands:
    - ipython -c "from autoviz import AutoViz_Class"
    - pip check
  requires:
    - ipython
    - pip

about:
  home: https://github.com/AutoViML/AutoViz
  summary: Automatically Visualize any dataset, any size with a single line of code
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
