{% set name = "autoviz" %}
{% set version = "0.1.804" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/autoviz-{{ version }}.tar.gz
  sha256: 8b6320aeeecde1899dd0ba3a77939440a48b9106e87faea78b190b15aef7692c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - xlrd
    - wordcloud
    - emoji
    - numpy <1.25.0
    - pandas
    - pyamg
    - matplotlib-base <=3.7.4
    - seaborn >=0.12.2
    - scikit-learn
    - statsmodels
    - nltk
    - textblob
    - holoviews ~=1.14.9
    - bokeh ~=2.4.2
    - hvplot ~=0.7.3
    - panel >=0.12.6
    - xgboost >=0.82,<1.7
    - fsspec >=0.8.3
    - typing-extensions >=4.1.1
    - pandas-dq >=1.29

test:
  commands:
    - ipython -c "from autoviz import AutoViz_Class"
    - pip check
  requires:
    - ipython
    - pip

about:
  home: https://github.com/AutoViML/AutoViz
  summary: Automatically Visualize any dataset, any size with a single line of code
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
